apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-app
  labels:
    name: nodejs-app-app
    version: ${project.version}
    buildNumber: b-${build.number}
spec:
  ports:
    - port: 10080
      targetPort: 10080
      protocol: TCP
      name: web-service
    - port: 4040
      targetPort: 4040
      protocol: TCP
      name: health-check-service
  # just like the selector in the deployment yaml,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    name: nodejs-app-app
    # version: ${project.version}
